#!/bin/bash
# MyVault Content Plugin Installation Guide
# The marketplace must be added from INSIDE Claude Code, not from bash

GITHUB_REPO="https://github.com/markiianb/myvault-content-plugin"
MARKETPLACE_NAME="myvault-marketplace"
PLUGIN_NAME="myvault-content"

echo "=== MyVault Content Plugin Installation ==="
echo ""
echo "⚠️  IMPORTANT: Marketplace commands must be run INSIDE Claude Code,"
echo "    not from the terminal."
echo ""
echo "Repository: $GITHUB_REPO (private)"
echo ""
echo "Prerequisites:"
echo "  ✓ You must be a collaborator on the GitHub repo"
echo "  ✓ GitHub credentials configured (test: ssh -T git@github.com)"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "STEP 1: Open Claude Code and run these commands:"
echo ""
echo "  /plugin marketplace add $GITHUB_REPO"
echo ""
echo "STEP 2: Install the plugin:"
echo ""
echo "  /plugin install $PLUGIN_NAME@$MARKETPLACE_NAME"
echo ""
echo "STEP 3: Restart Claude Code"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "After installation, you'll have these commands:"
echo "  /myvault:research [topic]"
echo "  /myvault:content-research [topic]"
echo "  /myvault:write [type] about [topic]"
echo "  /myvault:edit [content]"
echo ""
echo "To update later, run inside Claude Code:"
echo "  /plugin marketplace update $MARKETPLACE_NAME"
echo ""
